name: CI

on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          # Read https://whichjdk.com/#tldr to understand the difference between different distributions
          # MacOS might be running openjdk 17 (https://whichjdk.com/#apple-silicon) but we want to run the latest LTS on Linux
          distribution: corretto
          java-version: 21

      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3

      # Setup Fastlane
      - name: Setup Fastlane
        run: bundle install

      - name: Build AAR and POM files
        run: bundle exec fastlane build_example_app
